### ISSUE TITLE
Where can I find BOM

### ISSUE THREAD

**Issue by TonderaiZR** [sparkfun/Edison_Console_Block#2]
Hello

Is the Bill of materials available on the github?

**Comment by ToniCorinne** [comment]
We are not currently including BOMs as separate files in our repositories, though this is something we are looking into. Currently, you'd need to run the bom.ulp on the Eagle files to export the BOM. For more information on working with Eagle files, check out our tutorials [here](https://learn.sparkfun.com/tutorials/tags/eagle).
